import { GoogleGenAI, Chat } from "@google/genai";
import { AI_SYSTEM_INSTRUCTION } from '../constants';

const apiKey = import.meta.env.VITE_GEMINI_API_KEY || '';

class GeminiService {
  private ai: GoogleGenAI | null = null;
  private chatSession: Chat | null = null;

  constructor() {
    if (apiKey) {
      this.ai = new GoogleGenAI({ apiKey });
    } else {
      console.warn("Gemini API Key is missing. Chat features will be disabled or mocked.");
    }
  }

  public initializeChat() {
    if (!this.ai) return;

    try {
      this.chatSession = this.ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
          systemInstruction: AI_SYSTEM_INSTRUCTION,
          temperature: 0.7,
        },
      });
    } catch (error) {
      console.error("Failed to initialize chat session", error);
    }
  }

  public async sendMessage(message: string): Promise<string> {
    if (!this.ai || !this.chatSession) {
      // Mock chat response
      await new Promise(r => setTimeout(r, 1000));
      return "I'm currently running in demo mode  I can't access my full brain right now, but I can tell you that Shalom is a great engineer!";
    }

    try {
      const response = await this.chatSession.sendMessage({ message });
      return response.text || "I didn't catch that.";
    } catch (error) {
      console.error("Error sending message to Gemini:", error);
      return "I encountered a glitch in the matrix. Please try again.";
    }
  }

  public async generateBlogPost(topic: string): Promise<string> {
    // make sure mock response to ensure UI always works
    const getMockContent = async () => {
       await new Promise(r => setTimeout(r, 1500));
       return `This is a simulated blog post about "${topic}".\n\nIn a live environment with a valid API key, the Gemini model would generate a comprehensive, witty, and insightful article here. \n\nHowever, since we are in demo mode, imagine a brilliant exposition on the future of technology, covering: \n1. The impact of ${topic} on modern web development.\n2. Performance implications for next-gen apps.\n3. Why every developer should care in 2026.\n\n(Generated by showzy.dev system)`;
    };

    if (!this.ai) {
      return await getMockContent();
    }

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: `Write a short, engaging blog post (approx 100-150 words) about: ${topic}. Format with Markdown. Return only the body content.`,
      });
      return response.text || await getMockContent();
    } catch (error) {
      console.warn("Gemini generation failed, falling back to mock", error);
      return await getMockContent();
    }
  }
}

export const geminiService = new GeminiService();